name: Build and Deploy App

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: build
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Installing packages
      run: npm ci
    
    - name: Building
      run: npm run build

    - name: Upload Production files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build

  deploy:
    name: Deployment
    needs:  build
    runs-on:  ubuntu-latest

    steps:
    - name: Download Production files
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir:  ./build
